# Generated by Django 4.0 on 2023-08-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
